### ISSUE TITLE
Implement Access Control

### ISSUE THREAD

**Issue by jnogle** [CruCentralCoast/CruFirebase#5]
Firebase allows for incredibly robust access control rules. These rules are setup in a similar fashion to the Validation rules and are just small JS conditional statements. One of the primary reasons for moving to Firebase is to allow better implementation of access control. For most data, an authenticated user will be able to read the data and an admin will be able to write to the data. For a small portion of data though, users will be granted editing privileges based on certain conditions (e.g. a Community Group Leader needs to edit the day of the week and time of their Community Group, but no one else should be able to edit it). This means that general access control rule groups for admins and schedulers will need to be setup to control access at a broad level, and that model specific access control rules should be implemented as well.

**Comment by fedorareis** [comment]
I think this is done, but I will need to test it after some of the other stuff is finished.
